### ISSUE TITLE
Gnucap: missing libreadline.so.7

### ISSUE THREAD

**Issue by williria** [termux/science-packages#11]
I have libreadline.so.8 installed, but gnucap ask for the older version.
Output of termux-info:
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.14-15071035-QB23093188 #1 SMP PREEMPT Mon Apr 8 23:23:33 KST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-J400M

**Comment by Grimler91** [comment]
Thanks for reporting! Will be fixed shortly

**Comment by Davoboss1** [comment]
It's fixed right.
