### ISSUE TITLE
OpenSCAD

### ISSUE THREAD

**Issue by anonimo82** [termux/science-packages#33]
This is a GREAT CLI CAD, it could be tought as ImageMagick of 3D.

**Package description**
Describe what this package do and why it should be available.
This is a parametric CAD, working from command line, that allows to do nearly whatever you can with apps like SketchUp.

**Link to home page and sources**
1. Home page: https://www.openscad.org/
2. Source code: https://github.com/openscad/openscad/

**Additional information**
Have you compiled or tried to compile the package on device? No
* If it didn't work then please provide the error you ran into /
* If it did work then please share any patches that you had to apply

Thanks for reading

**Comment by anonimo82** [comment]
Oh, I see now.
Thanks

**Comment by xeffyr** [comment]
OpenSCAD should be now available.
`pkg install openscad` - if you have `science-repo` already installed.

**Comment by anonimo82** [comment]
I get this error: The following packages have unmet dependencies:
 openscad : Depends: double-conversion but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Grimler91** [comment]
@anonimo82 did you run `pkg install openscad`? Looks like `apt update` hasn't been run in a while perhaps

**Comment by Grimler91** [comment]
I tried running one of the example and output as png, but got a warning that openscad hasn't been built with openCSG support, and the PNG is empty. Not sure if that's expected? 
```
openscad -o test.png $PREFIX/share/openscad/examples/Basics/text_on_cube.scad
Could not initialize localization.
ECHO: version = [2019, 10, 26]
Compiling design (CSG Products normalization)...
Normalized CSG tree has 7 elements
This openscad was built without OpenCSG support
```

**Comment by xeffyr** [comment]
Should libpng be added as dependency ?

**Comment by Grimler91** [comment]
Archlinux doesn't list libpng as dependency so I guess it shouldn't be necessary

**Comment by xeffyr** [comment]
`ldd` tells this:
```
[xeffyr]:~/Downloads:$ ldd openscad | grep png
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007da306bc8000)
```

**Comment by Grimler91** [comment]
Alright, yeah, we can list it in dependencies, but it is pulled in here as well so won't change the behaviour when trying to create a png unfortunately

**Comment by xeffyr** [comment]
Pulled but not linked. Maybe something should be enabled in configure flags.
