### ISSUE TITLE
Preserve commit history when moving packages

### ISSUE THREAD

**Issue by danieldjewell** [termux/science-packages#47]
I discovered that texlive was moved to science-packages in commit  a5145df8f3920ba59d850146ead8b42eb43b4514 but the commit history was not preserved, making it very difficult to use things like 'git blame' (not to "blame" someone of course, but to easily view what parts of a file changed when.)

It appears that the files as they existed on May 1 were copied and committed into science-packages as if they were new files. 

There is an alternative that should allow for the preservation of edit/commit history -- see: https://stackoverflow.com/questions/1365541/how-to-move-files-from-one-git-repo-to-another-not-a-clone-preserving-history and https://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by Grimler91** [comment]
Yeah, thanks for the tip. I used something like that when moving games and science packages before, but I kind of forgot about it when moving texlive. Anyways, thanks, will stick to this technique in the future
