### ISSUE TITLE
OpenSCAD cannot find library "libboost_filesystem.so.1.72.0"

### ISSUE THREAD

**Issue by lonesock8233** [termux/science-packages#48]
Hello,

I installed the headless build of openscad using the package manager, but get the following message when I try to run the program:

`CANNOT LINK EXECUTABLE "openscad": library "libboost_filesystem.so.1.72.0" not found`

I checked my usr/lib, and I have "libboost_filesystem.so.1.73.0", the newer version. 

Is it possible to update openscad to work with the newer library? If so, how?

Thanks for any help you can give.

In case it is helpful, below is my termux-info:

Packages CPU architecture:
aarch64
Subscribed repositories:
\# sources.list
deb https://termux.org/packages/ stable main
\# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
\# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Fri Jul 3 00:55:28 CST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1917

**Comment by Grimler91** [comment]
Hi,

Thanks for reporting! 

Packages depending on boost needs to be bumped after every boost update, and I had not done that for openscad. openscad-2019.05-2 should be available now, and work with boost 1.73.

Let me know if you encounter any other problems with the package!
