### ISSUE TITLE
openmpi: needs libomp.so

### ISSUE THREAD

**Issue by xeffyr** [termux/science-packages#56]
**Problem description**

![Screenshot_20210116-220104](https://user-images.githubusercontent.com/25881154/104821785-e94c9f80-5846-11eb-9c47-dbfef63af078.png)

**Steps to reproduce**

```
pkg install openmpi
mpicc
```

**Expected behavior**

There shouldn't be any linking errors.

Probably it just needs to be recompiled as `build-package.sh` now provides a compiler flag for using a static libomp.

**Comment by Grimler91** [comment]
Thanks, should be fixed after reconfiguring and re-building: https://github.com/termux/science-packages/commit/bbc0d6081dccf61aad08a73ac7074a4280d8df29
