### ISSUE TITLE
Spatialite

### ISSUE THREAD

**Issue by dead10ck** [termux/science-packages#58]
# Spatialite

It would be great if the Spatialite library was packaged for termux. gdal is already packaged, but since spatialite is missing, it is compiled without Spatialite support, so it would be great if, once there is a Spatialite package, if the gdal package could also be compiled with Spatialite support.

## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
1. Home page: https://www.gaia-gis.it/fossil/libspatialite/index
2. Source code: https://www.gaia-gis.it/fossil/libspatialite/dir?ci=tip

**Additional information**

Have you compiled or tried to compile the package on device?

No, my use case is to use it with gdal, which is already a termux package.

**Comment by Grimler91** [comment]
Will add this when the CI build of https://github.com/termux/science-packages/issues/58 succeeds. Basically untested so please let me know if you notice any issues.

Also let me know if you have use for other gdal features, the version we are shipping is pretty bare-boned
