### ISSUE TITLE
texlive-full installation fails

### ISSUE THREAD

**Issue by leomayer** [termux/science-packages#61]
**Problem description**

I have installed with Termux 1.04 `texlive-full` successfully on my tablet. I uninstalled Termux and reinstalled 1.07. 
`pkg install texlive-full` installs successfully all packages.
Running the command `pdftex` returns

```
The program pdftex is not installed. Install it by execturing:
pkg install texlive-bin
```

Running the above mentioned command installs 0 packages and nothing is changed.

**Expected behavior**
After installation I would like to run the commands. But somehow they are not available.

**Additional information**

* Termux application version: 1.07
* Android OS version: 10
* Device model: Huawei

**Comment by Grimler91** [comment]
I guess it is a problem with the postinst script somehow. If you run `texlinks` all the links should be created and it hopefully works

**Comment by leomayer** [comment]
Hmmmm.... running `texlinks` tells me to install `texlive-bin` . Which brings me back to the origin of this issue since I cannot do much.
BTW: Where should this `texlinks` be located - perhaps I can execute it manually.

**Comment by Grimler91** [comment]
Maybe PATH is not set correctly yet. Have you opened a new session or run `source $PREFIX/etc/profile.d/texlive.sh`?

What shell are you using?

texlinks should be in `$PREFIX/bin/texlive/` and be a symlink to `$PREFIX/share/texlive/texmf-dist/scripts/texlive-extra/texlinks.sh`, does that file exist?

**Comment by leomayer** [comment]
Running the first command helped and resolved the issue. 

I'm running on ˋfishˋ. Execution of ˋtexlinkˋ succeeded as well. 
Thx

**Comment by leomayer** [comment]
I closed little bit tooo early. Running the first command helps. But when I close the session(s) with ˋexitˋ and than reopen termux I need to run again the same command. It seems like the setting is not persisted :-/

**Comment by Grimler91** [comment]
Right, I have not created a profile script for fish so the path is never updated for that shell. 

From a quick search it looks like this should work for fish:

```fish
set PATH $PATH $PREFIX/bin/texlive
export PATH
```

Try putting this in $PREFIX/etc/profile.d/texlive.fish and then close termux fully and open it again. The profile scripts are not sourced as often as for example .bashrc so you probably need to close termux fully in between

**Comment by leomayer** [comment]
I didn't succeed much with your proposal. But this [one](https://stackoverflow.com/a/61882414/325868) helped. 

ˋˋˋ
contains $PREFIX/bin/texlive fish_user_paths; or set -Ua fish_user_paths $PREFIX/bin/texlive
ˋˋˋ

Does this apply as well to other package installation via fish? 

I think you can close nevertheless this issue.

**Comment by Grimler91** [comment]
Great! I'll add it to the package, thanks for testing!

> Does this apply as well to other package installation via fish?

You mean if other packages might have problems?
Very few needs this type of customization, and some of them already have fish support. But please open issues if you notice problems
