### ISSUE TITLE
PostGIS

### ISSUE THREAD

**Issue by dead10ck** [termux/science-packages#62]
**Package description**
PostGIS is an extension to PostgreSQL to do geospatial queries. I would like to use it for a project involving doing a mass import into OpenStreetMap.

**Link to home page and sources**
1. Home page: https://postgis.net/
2. Source code: https://postgis.net/source/

**Additional information**
Have you compiled or tried to compile the package on device?

No

**Comment by Grimler91** [comment]
Requested in https://github.com/termux/science-packages/issues/55, where another user shared a script for compiling and installing it on device. Cross-compiling it requires some work as it tries to run the cross-compiled pg_config tool

**Comment by dead10ck** [comment]
Ah, sorry about that, thank you.
