### ISSUE TITLE
 libhdf5-static installation error 

### ISSUE THREAD

**Issue by dipayand** [termux/science-packages#66]
I get the following error:

The following packages have unmet dependencies:
 libhdf5-static : Depends: libhdf5 (= 1.12.0-2) but 1.12.0-3 is to be installed

**Comment by Grimler91** [comment]
Should be fixed now please try again.

libhdf5-static for 1.12.0-3 was missing from the repo, I had forgotten to handle `-static` packages in the script I am using, and apparently I forgot to add libhdf5-static 1.12.0-3 after fixing that.
Thanks for reporting!

**Comment by dipayand** [comment]
Yes it works now... closing the issue
